# Configurations for SCONFGenerator
# windows8.sxfm
nameKB = "windows8.sxfm"
kbPath = "./data/fms/"
confPath = "./data/confs/windows8/"

# V2
sizeSCONFs = [1, 2]
maxCombinations = 110000

outputFolder = "./data/sconfs/windows8/"