# Configurations for SCONFGenerator
# ubuntu.sxfm
nameKB = "ubuntu.sxfm"
kbPath = "./data/fms/"
confPath = "./data/confs/ubuntu/"

# V2
sizeSCONFs = [4, 8]
maxCombinations = 10000

outputFolder = "./data/sconfs/ubuntu/"