# Configurations for SCONFGenerator
# ubuntu.sxfm
nameKB = "ubuntu.sxfm"
kbPath = "./data/fms/"
confPath = "./data/confs/ubuntu/"

# V2
sizeSCONFs = [1, 2]
maxCombinations = 110000

outputFolder = "./data/sconfs/ubuntu/"