# Configurations for SCONFGenerator
# fqa.sxfm
nameKB = "fqa.sxfm"
kbPath = "./data/fms/"
confPath = "./data/confs/fqa/"

# V2
sizeSCONFs = [1, 2]
maxCombinations = 110000

outputFolder = "./data/sconfs/fqa/"